import type * as monaco from "monaco-editor";

export const EDITOR_ACTIONS_STORAGE_KEY = "comet-editor-actions";

export const EDITOR_DEFAULT_OPTIONS: monaco.editor.IStandaloneEditorConstructionOptions =
	{
		fontFamily: "JetBrains Mono, Consolas, monospace",
		minimap: {
			enabled: false,
			scale: 100,
			showSlider: "mouseover",
			renderCharacters: true,
			maxColumn: 80,
			size: "proportional",
			side: "right",
		},
		scrollBeyondLastLine: false,
		renderLineHighlight: "line",
		padding: { top: 10, bottom: 50 },
		quickSuggestions: false,
		parameterHints: { enabled: false },
		suggestOnTriggerCharacters: false,
		acceptSuggestionOnEnter: "off",
		suggestSelection: "first",
		scrollbar: {
			vertical: "visible",
			horizontal: "hidden",
			verticalScrollbarSize: 10,
			horizontalScrollbarSize: 10,
			useShadows: false,
		},
		smoothScrolling: true,
		insertSpaces: true,
		roundedSelection: true,
		autoClosingBrackets: "always",
		autoClosingQuotes: "always",
		lineNumbersMinChars: 3,
		glyphMargin: true,
		folding: false,
		matchBrackets: "always",
		find: {
			addExtraSpaceOnTop: false,
			autoFindInSelection: "never",
			seedSearchStringFromSelection: "always",
		},
		contextmenu: false,
		links: false,
		suggest: {
			showIcons: false,
			showStatusBar: false,
			showInlineDetails: false,
			preview: false,
			showMethods: false,
			showFunctions: false,
			showConstructors: false,
			showDeprecated: false,
			showFields: false,
			showVariables: false,
			showClasses: false,
			showStructs: false,
			showInterfaces: false,
			showModules: false,
			showProperties: false,
			showEvents: false,
			showOperators: false,
			showUnits: false,
			showValues: false,
			showConstants: false,
			showEnums: false,
			showEnumMembers: false,
			showKeywords: false,
			showWords: false,
			showColors: false,
			showFiles: false,
			showReferences: false,
			showFolders: false,
			showTypeParameters: false,
			showSnippets: false,
		},
		stickyScroll: { enabled: false },
		hover: { enabled: false },
		multiCursorModifier: "alt",
	} as const;
